CREATE OR REPLACE TYPE ty_material AS OBJECT
(
  db_id NUMBER,
  nev   VARCHAR2(30),
  ar    NUMBER,

  CONSTRUCTOR FUNCTION ty_material RETURN SELF AS RESULT
)
/
CREATE OR REPLACE TYPE BODY ty_material IS

  CONSTRUCTOR FUNCTION ty_material RETURN SELF AS RESULT IS
  BEGIN
    RETURN;
  END;

END;
/
